const NAMESPACE = 'PROJECTS';
export const FETCH_PROJECTS = `${NAMESPACE}/FETCH_PROJECTS`;
export const PROJECTS_SUCCESS = `${NAMESPACE}/PROJECTS_SUCCESS`;
export const PROJECTS_FAILED = `${NAMESPACE}/PROJECTS_FAILED`;
export const CLEAR_PROJECTS = `${NAMESPACE}/CLEAR_PROJECTS`;

export const FETCH_SINGLE_PROJECT = `${NAMESPACE}/FETCH_SINGLE_PROJECT`;
export const SINGLE_PROJECT_SUCCESS = `${NAMESPACE}/SINGLE_PROJECT_SUCCESS`;
export const SINGLE_PROJECT_FAILED = `${NAMESPACE}/SINGLE_PROJECT_FAILED`;
export const CLEAR_SINGLE_PROJECT = `${NAMESPACE}/CLEAR_SINGLE_PROJECT`;

export const EDIT_PROJECT = `${NAMESPACE}/EDIT_PROJECT`;
export const EDIT_PROJECT_SUCCESS = `${NAMESPACE}/EDIT_PROJECT_SUCCESS`;
export const EDIT_PROJECT_FAILED = `${NAMESPACE}/EDIT_PROJECT_FAILED`;
export const CLEAR_EDIT_PROJECT = `${NAMESPACE}/CLEAR_EDIT_PROJECT`;

export const DELETE_PROJECT = `${NAMESPACE}/DELETE_PROJECT`;
export const DELETE_PROJECT_SUCCESS = `${NAMESPACE}/DELETE_PROJECT_SUCCESS`;
export const DELETE_PROJECT_FAILED = `${NAMESPACE}/DELETE_PROJECT_FAILED`;
export const CLEAR_DELETE_PROJECT = `${NAMESPACE}/CLEAR_DELETE_PROJECT`;

export const ADD_PROJECT = `${NAMESPACE}/ADD_PROJECT`;
export const ADD_PROJECT_SUCCESS = `${NAMESPACE}/ADD_PROJECT_SUCCESS`;
export const ADD_PROJECT_FAILED = `${NAMESPACE}/ADD_PROJECT_FAILED`;
export const CLEAR_ADD_PROJECT = `${NAMESPACE}/CLEAR_ADD_PROJECT`;
