# Generated by Django 3.0.8 on 2020-08-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lob_id', models.IntegerField()),
                ('workflow_id', models.IntegerField()),
                ('project_type_id', models.IntegerField()),
                ('annotation_id', models.IntegerField()),
                ('ds_id', models.IntegerField()),
                ('project_name', models.CharField(max_length=100)),
                ('project_desc', models.CharField(max_length=400)),
                ('project_start_date', models.CharField(max_length=30)),
                ('project_recurrence_start_date', models.CharField(max_length=30)),
                ('project_recurrence_end_date', models.CharField(max_length=30)),
                ('project_end_date', models.CharField(max_length=30)),
                ('project_model_name', models.CharField(max_length=500)),
                ('project_status_id', models.IntegerField()),
                ('annotators_per_record', models.IntegerField()),
            ],
        ),
    ]
