# Generated by Django 3.0.8 on 2020-08-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectdetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetails',
            name='num_tasks',
            field=models.CharField(default='', max_length=100),
        ),
    ]
