# Generated by Django 3.0.8 on 2020-08-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectdetails', '0002_projectdetails_num_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetails',
            name='complete_percent',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='to_reassign',
            field=models.CharField(default='', max_length=100),
        ),
    ]
