# Generated by Django 3.0.8 on 2020-08-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectdetails', '0003_auto_20200805_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetails',
            name='annotators_list',
            field=models.CharField(default='', max_length=9999999),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='reviewers_list',
            field=models.CharField(default='', max_length=9999999),
        ),
        migrations.AddField(
            model_name='projectdetails',
            name='workflow_roles',
            field=models.CharField(default='', max_length=100),
        ),
    ]
