# Generated by Django 3.0.8 on 2020-08-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_lan_id', models.CharField(max_length=20)),
                ('project_id', models.CharField(max_length=20)),
                ('lob_id', models.CharField(max_length=20)),
                ('role_id', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('creation_date', models.CharField(max_length=40)),
                ('access_expiry_date', models.CharField(max_length=40)),
                ('active', models.CharField(max_length=10)),
            ],
        ),
    ]
