# Generated by Django 3.0.8 on 2020-08-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='access_expiry_date',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='project_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='role_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_lan_id',
            field=models.CharField(default='', max_length=20),
        ),
    ]
