# Generated by Django 3.0.8 on 2020-08-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='role_desc',
            field=models.CharField(default='', max_length=400),
        ),
    ]
