const NAMESPACE = 'ROLES';
export const FETCH_ROLES = `${NAMESPACE}/FETCH_ROLES`;
export const ROLES_SUCCESS = `${NAMESPACE}/ROLES_SUCCESS`;
export const ROLES_FAILED = `${NAMESPACE}/ROLES_FAILED`;
export const CLEAR_ROLES = `${NAMESPACE}/CLEAR_ROLES`;

export const FETCH_SINGLE_ROLE = `${NAMESPACE}/FETCH_SINGLE_ROLE`;
export const SINGLE_ROLE_SUCCESS = `${NAMESPACE}/SINGLE_ROLE_SUCCESS`;
export const SINGLE_ROLE_FAILED = `${NAMESPACE}/SINGLE_ROLE_FAILED`;
export const CLEAR_SINGLE_ROLE = `${NAMESPACE}/CLEAR_SINGLE_ROLE`;

export const EDIT_ROLE = `${NAMESPACE}/EDIT_ROLE`;
export const EDIT_ROLE_SUCCESS = `${NAMESPACE}/EDIT_ROLE_SUCCESS`;
export const EDIT_ROLE_FAILED = `${NAMESPACE}/EDIT_ROLE_FAILED`;
export const CLEAR_EDIT_ROLE = `${NAMESPACE}/CLEAR_EDIT_ROLE`;

export const DELETE_ROLE = `${NAMESPACE}/DELETE_ROLE`;
export const DELETE_ROLE_SUCCESS = `${NAMESPACE}/DELETE_ROLE_SUCCESS`;
export const DELETE_ROLE_FAILED = `${NAMESPACE}/DELETE_ROLE_FAILED`;
export const CLEAR_DELETE_ROLE = `${NAMESPACE}/CLEAR_DELETE_ROLE`;

export const ADD_ROLE = `${NAMESPACE}/ADD_ROLE`;
export const ADD_ROLE_SUCCESS = `${NAMESPACE}/ADD_ROLE_SUCCESS`;
export const ADD_ROLE_FAILED = `${NAMESPACE}/ADD_ROLE_FAILED`;
export const CLEAR_ADD_ROLE = `${NAMESPACE}/CLEAR_ADD_ROLE`;
