const NAMESPACE = 'users';
export const FETCH_USERS = `${NAMESPACE}/FETCH_USERS`;
export const USERS_SUCCESS = `${NAMESPACE}/USERS_SUCCESS`;
export const USERS_FAILED = `${NAMESPACE}/USERS_FAILED`;
export const CLEAR_USERS = `${NAMESPACE}/CLEAR_USERS`;

export const FETCH_SINGLE_USER = `${NAMESPACE}/FETCH_SINGLE_USER`;
export const SINGLE_USER_SUCCESS = `${NAMESPACE}/SINGLE_USER_SUCCESS`;
export const SINGLE_USER_FAILED = `${NAMESPACE}/SINGLE_USER_FAILED`;
export const CLEAR_SINGLE_USER = `${NAMESPACE}/CLEAR_SINGLE_USER`;

export const EDIT_USER = `${NAMESPACE}/EDIT_USER`;
export const EDIT_USER_SUCCESS = `${NAMESPACE}/EDIT_USER_SUCCESS`;
export const EDIT_USER_FAILED = `${NAMESPACE}/EDIT_USER_FAILED`;
export const CLEAR_EDIT_USER = `${NAMESPACE}/CLEAR_EDIT_USER`;

export const DELETE_USER = `${NAMESPACE}/DELETE_USER`;
export const DELETE_USER_SUCCESS = `${NAMESPACE}/DELETE_USER_SUCCESS`;
export const DELETE_USER_FAILED = `${NAMESPACE}/DELETE_USER_FAILED`;
export const CLEAR_DELETE_USER = `${NAMESPACE}/CLEAR_DELETE_USER`;

export const ADD_USER = `${NAMESPACE}/ADD_USER`;
export const ADD_USER_SUCCESS = `${NAMESPACE}/ADD_USER_SUCCESS`;
export const ADD_USER_FAILED = `${NAMESPACE}/ADD_USER_FAILED`;
export const CLEAR_ADD_USER = `${NAMESPACE}/CLEAR_ADD_USER`;
